extends: default

rules:
  line-length:
    max: 160
    ignore: |
      *-lock.yaml
      .github/workflows/codeql.yaml
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
